---
name: Pull request build

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint project
    permissions:
      pull-requests: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint code base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GITIGNORED_FILES: true
          IGNORE_GENERATED_FILES: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JAVA: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_XML: true
          VALIDATE_YAML: true

  build:
    needs: lint
    runs-on: ubuntu-latest
    name: Build project
    permissions:
      checks: write
      pull-requests: write
    env:
      MAIN_JAVA_VER: 11
    strategy:
      matrix:
        java: [11, 17]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Verify the project and create coverage report
        run: mvn verify jacoco:report -B -ff

      - name: Report test summary
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ matrix.java == env.MAIN_JAVA_VER  && always() }}
        with:
          test_changes_limit: 0
          files: ./target/junit-platform/TEST-junit-jupiter.xml

      - name: Push coverage report
        uses: codecov/codecov-action@v3
        if: ${{ matrix.java == env.MAIN_JAVA_VER }}
        with:
          file: ./target/site/jacoco/jacoco.xml
