---
name: Pre-release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-release:
    runs-on: ubuntu-latest
    name: Build and pre-release latest
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Cache Maven Repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Verify Project
        run: mvn verify jacoco:report -B -ff

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: latest

      - name: Push to CodeCov
        uses: codecov/codecov-action@v1.5.0
        with:
          file: target/site/jacoco/jacoco.xml
          flags: unit-tests
          name: hebcal-api-codecov
          fail_ci_if_error: true
