---
name: Pre-release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-release:
    runs-on: ubuntu-latest
    environment: staging
    name: Build and pre-release and deploy to GPR
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Cache Maven Repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Get current project version
        id: currentVersion
        # yamllint disable-line rule:line-length
        run: echo "::set-output name=text::$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)"

      - name: Deploy to GPR
        if: endsWith(steps.currentVersion.outputs.text, '-SNAPSHOT')
        run: mvn deploy jacoco:report -Pprepare-deployment,sign-deployment,deploy-github -B -ff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: early-access
          title: early-access

      - name: Push to CodeCov
        uses: codecov/codecov-action@v2.0.1
        with:
          file: target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
