---
name: Pre-release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-release:
    runs-on: ubuntu-latest
    environment: staging
    name: Build and pre-release and deploy to GPR
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Cache Maven Repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Deploy to GPR
        run: mvn deploy -Pprepare-deployment,sign-deployment -B -ff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: early-access
          title: early-access

      - name: Push to CodeCov
        uses: codecov/codecov-action@v1.5.2
        with:
          file: target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
