---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release semantic version
        required: true
      next_iteration:
        description: Next release snapshot iteration
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: deployment
    name: Build release and push to OSSRH
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Cache Maven Repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Configure git
        run: |
          git config --global user.name "${{ secrets.GIT_VERIFIED_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_VERIFIED_USER_EMAIL }}"
          git config --global commit.gpgSign true
          git config --global tag.gpgSign true
          git config --global user.signingkey ${{ secrets.GPG_PRIVATE_KEY_ID }}
          git pull

      - name: Initiate an ssh agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to OSSRH
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: >
          mvn release:prepare -B -ff
          -Dtag=${{ github.event.inputs.version }}
          -DreleaseVersion=${{ github.event.inputs.version }}
          -DdevelopmentVersion=${{ github.event.inputs.next_iteration }}
          && mvn release:perform -B -ff

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.version }}
          title: ${{ github.event.inputs.version }}
          prerelease: false

      - name: Dispatch release event
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.EVENT_DISPATCH_PAT }}
          event-type: hebcal-api-released

      - name: Tweet new release
        uses: lazy-actions/tweet-action@1.0.1
        env:
          RELEASE_TAG: ${{ github.event.inputs.version }}
        with:
          oauth_consumer_key: ${{ secrets.TWITTER_API_KEY }}
          oauth_consumer_secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
          oauth_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          oauth_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          message: |
            🚀🎉 Hebcal-api ${{ env.RELEASE_TAG }} has been released! 🎉🚀
            ${{ github.event.repository.html_url }}/releases/tag/${{ env.RELEASE_TAG }}

            #hebcal-java-api
