---
name: Release

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: deployment
    name: Build release and push to OSSRH
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN

      - name: Cache Maven Repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Verify Project
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        run: |
          mvn release:prepare -B -ff
          mvn release:perform -B -ff

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false

      - name: Dispatch release event
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.EVENT_DISPATCH_PAT }}
          event-type: hebcal-api-released

      - name: Tweet new release
        uses: lazy-actions/tweet-action@1.0.1
        env:
          RELEASE_TAG: ${{ steps.create_release.outputs.automatic_releases_tag }}
        with:
          oauth_consumer_key: ${{ secrets.TWITTER_API_KEY }}
          oauth_consumer_secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
          oauth_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          oauth_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          message: |
            🚀🎉 Hebcal-api ${{ env.RELEASE_TAG }} has been released! 🎉🚀
            ${{ github.event.repository.html_url }}/releases/tag/${{ env.RELEASE_TAG }}

            #hebcal-java-api
