---
name: Release

on:
  workflow_dispatch:
    inputs:
      tweet:
        description: "Tweet new release?"
        required: false
        default: "yes"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: deployment
    name: Build, publish, release, and announce
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Java 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: adopt
          java-version: 11
          cache: maven
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Configure git
        run: |
          git config --global user.name "${{ secrets.GIT_VERIFIED_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_VERIFIED_USER_EMAIL }}"
          git config --global commit.gpgSign true
          git config --global tag.gpgSign true
          git config --global user.signingkey ${{ secrets.GPG_PRIVATE_KEY_ID }}

      - name: Determine version and create changelog
        id: bumper
        uses: tomerfi/version-bumper-action@1.0.1
        with:
          changelog: true
          label: -SNAPSHOT

      - name: Initiate an ssh agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to OSSRH
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: >
          mvn release:prepare -B -ff
          -Dtag=${{ steps.bumper.outputs.new_version }}
          -DreleaseVersion=${{ steps.bumper.outputs.new_version }}
          -DdevelopmentVersion=${{ steps.bumper.outputs.next_dev_iteration}}
          && mvn release:perform -B -ff

      - name: Dispatch release event for jbang catalog
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.EVENT_DISPATCH_PAT }}
          event-type: hebcal-api-released
          repository: TomerFi/jbang-catalog
          client-payload: '{"release": "${{ steps.bumper.outputs.new_version }}"}'

      - name: Release to GitHub
        id: gh_release
        uses: ncipollo/release-action@v1.8.9
        with:
          bodyFile: changelog-${{ steps.bumper.outputs.new_version }}.md
          tag: ${{ steps.bumper.outputs.new_version }}

      - name: Update readme usage section
        run: |
          sed -i 's/<version>.*<\/version>/<version>${{ steps.bumper.outputs.new_version }}<\/version>/g' .github/README.md

      - name: Push modifications
        run: |
          git add .github/README.md
          git commit -m "docs: updated usage section with ${{ steps.bumper.outputs.new_version }} [skip ci]"
          git push

      - name: Tweet new release
        if: ${{ github.event.inputs.tweet == 'yes' }}
        uses: lazy-actions/tweet-action@1.0.1
        with:
          oauth_consumer_key: ${{ secrets.TWITTER_API_KEY }}
          oauth_consumer_secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
          oauth_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          oauth_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          message: |
            🚀🎉 Hebcal-api ${{ steps.bumper.outputs.new_version }} has been released! 🎉🚀
            ${{ steps.gh_release.outputs.html_url }}

            #hebcal_java_api
